### ISSUE TITLE
Multi-thread example

### ISSUE THREAD

**Issue by mohsenomidi** [moki/simple-libh2o-server#1]
Dear @moki 

is it possible to add the multi-thread listener on single port as a feature?

Regards,

**Comment by moki** [comment]
@mohsenomidi if you mean dealing with concurrency of multiple clients on the server by spawning thread per client, then i am afraid this is not something i am interested in.
I would recommend checking out http://www.kegel.com/c10k.html for why event loop is the way to go for the real world application.
If i misunderstood you, feel free to follow up.

**Comment by mohsenomidi** [comment]
as i understood this is implemented in libh2o with evloop these functions already exists : `h2o_multithread_create_thread` and `h2o_multithread_send_message` and `on_config_num_threads_add_cpu` no need to implement the threading, but i am not completely sure. 
if it is not implemented in libh2o and need extrenal implementation, forget about it, it should be implemented internally to handle requests in socket layer, the wrapper on library is not a correct way.

**Comment by moki** [comment]
There is no documentation and the only way to get around is to consult the source code, following are wrappers for pthreads.
https://github.com/h2o/h2o/blob/master/include/h2o/multithread.h#L76-L83
https://github.com/h2o/h2o/blob/master/lib/common/multithread.c#L192-L233
